name: Build Helm

on:
  push:
    branches:
      - "main"
    paths:
      - "assignment-3/**"
      - ".github/workflows/build-helm.yml"

concurrency: build-helm

jobs:
  helm-build:
    runs-on: ubuntu-latest
    name: Helm Build
    env:
        AWS_REGION: ap-south-1
        AWS_DEFAULT_REGION: us-east-1
        VERSION: "1.0"
    permissions:
        id-token: write
        contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: azure/setup-helm@v3
        with:
            version: '3.12.3'

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
            aws ecr get-login-password \
            --region ${{ env.AWS_REGION }} | helm registry login \
            --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      
      - name: Package and publish helm chart
        working-directory: 'assignment-3/helm'
        run: |
            helm package .
            helm push $(ls snigdhajyoti-joe-microservices-helm*.tgz) oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/
