name: Build App

on:
  push:
    branches:
      - "main"
    paths:
      - "assignment-1/**"
      - ".github/workflows/build-app.yml"

concurrency: build-app

jobs:
  build-app:
    runs-on: ubuntu-latest
    name: Build App
    env:
        AWS_REGION: ap-south-1
        AWS_DEFAULT_REGION: us-east-1
        VERSION: "1.0"
    permissions:
        id-token: write
        contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - id: metadata
        name: Compute Metadata
        run: |
            echo "current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - id: docker_image_amd
        name: Build Image AMD
        uses: docker/build-push-action@v5
        with:
            context: "assignment-1"
            no-cache: true
            push: true
            tags: ${{ steps.login-ecr.outputs.registry }}/snigdhajyoti-hello-world:latest-amd,${{ steps.login-ecr.outputs.registry }}/snigdhajyoti-hello-world:${{ env.VERSION }}-amd
            platforms: linux/amd64
            labels: |
                org.opencontainers.image.title=snigdhajyoti-hello-world
                org.opencontainers.image.url=${{ github.repositoryUrl }}
                org.opencontainers.image.version=${{ env.VERSION }}
                org.opencontainers.image.created=${{ steps.metadata.outputs.current_date }}
                org.opencontainers.image.revision=${{ github.sha }}

      - id: docker_image_arm
        name: Build Image ARM
        uses: docker/build-push-action@v5
        with:
            context: "assignment-1"
            no-cache: true
            push: true
            tags: ${{ steps.login-ecr.outputs.registry }}/snigdhajyoti-hello-world:latest-arm,${{ steps.login-ecr.outputs.registry }}/snigdhajyoti-hello-world:${{ env.VERSION }}-arm
            platforms: linux/arm64/v8
            labels: |
                org.opencontainers.image.title=snigdhajyoti-hello-world
                org.opencontainers.image.url=${{ github.repositoryUrl }}
                org.opencontainers.image.version=${{ env.VERSION }}
                org.opencontainers.image.created=${{ steps.metadata.outputs.current_date }}
                org.opencontainers.image.revision=${{ github.sha }}
    
      - name: Summary
        run: |
            {
            echo -e "# Image: snigdhajyoti-hello-world\n"
            echo '<details>'
            echo '<summary>Details</summary>'
            echo -e '\n```'
            echo -e 'AMD64:\n'
            echo -e "${{ steps.docker_image_amd.outputs.metadata }}"
            echo -e 'ARM64:\n'
            echo -e "${{ steps.docker_image_amd.outputs.metadata }}"
            echo -e '```'
            echo '</details>'
            echo -e '\n'
            } >> $GITHUB_STEP_SUMMARY